spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Q1451619620a
    url: jdbc:mysql://rm-uf6e9nw926b6h4e29o.mysql.rds.aliyuncs.com/security?characterEncoding=utf-8&useSSl=fasle
  session:
    store-type: none
  redis:
    host: 192.168.6.9
#security:
#  basic:
#    enabled: false

#nxs:
#  security:
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user,/user/*
#    browser:
#      loginPage: /signIn.html
#      loginType: REDIRECT