spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Q1451619620a
    url: jdbc:mysql://rm-uf6e9nw926b6h4e29o.mysql.rds.aliyuncs.com/security?characterEncoding=utf-8&useSSl=fasle
  session:
    store-type: redis
  redis:
    host: 192.168.6.12

#security:
#  basic:
#    enabled: false

nxs:
  security:
    social:
      qq:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin
    filterProcessesUrl:
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user,/user/*
    browser:
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
server:
  session:
    timeout: 10
  port: 8080
security:
  oauth2:
    client:
      client-id: nxs
      client-secret: nxs
#      loginPage: /signIn.html
#      loginType: REDIRECT
